### DISCUSSION TITLE
Ignore path parameter name changes?

### DISCUSSION THREAD

**Discussion by reuvenharrison** [Tufin/oasdiff#212] [Q&A]
How should diff handle path parameter renaming?

For example:
/books/{id} -> /books/{bookId}

Our options are:
1. Display such changes at the path level:
```
endpoints:
    added:
        - method: GET
          path: /books/{bookId}
    deleted:
        - method: GET
          path: /books/{id}
```
2. Display such changes at the param level:
```
paths:
    modified:
        /books/{id}:
            parameters:
                modified:
                    path:
                        id:
                            name:
                                from: id
                                to: bookId
```
4. Ignore such changes
5. Make it configurable

See https://github.com/Tufin/oasdiff/issues/202
