### DISCUSSION TITLE
How to run oasdiff as a *GitLab* pipeline step?

### DISCUSSION THREAD

**Discussion by diegocmsantos** [Tufin/oasdiff#410] [Q&A]
Hi, trying to run this as a step in my .gitlab-ci.yaml file.

Does anyone knows how to do this?

thank you

**Comment by edanko** [comment]
Hello there!
You need to get the master spec, any way you like, and compare to merge request one, for example (not tested yet):
```
compare_specs:
  stage: test
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - cp api/openapi_spec.yaml openapi_spec_mr.yaml
    - git checkout main
    - cp api/openapi_spec.yaml openapi_spec_master.yaml
    - oasdiff breaking openapi_spec_master.yaml openapi_spec_mr.yaml
  only:
    - merge_requests
```
