### DISCUSSION TITLE
Configurable selection of checks and their severity levels

### DISCUSSION THREAD

**Discussion by Patrick-Bayer** [Tufin/oasdiff#572] [Ideas]
Hi all,

i wrote a test to ensure backwards compatibility of our API that fails when the `oasdiff breaking` command returns a warning or an error.
I discovered that changing the type of a property from 'number' to 'integer' and its format from 'float' to 'int64' is not considered a breaking change. To us, it is a breaking change and therefore we want our test to fail.
With that use case in mind, is it possible to configure the severity level of checks and the selection of checks performed?

Best regards
Patrick

**Comment by reuvenharrison** [comment]
Hi @Patrick-Bayer,
Could you please share the 2 specs that you are comparing so I can see the context of the change.

This is important to determine if this is a bug or not.
For example: a change in request will behave differently than a change in response, and there are many other factors that can affect the result.

Thanks,
Reuven

**Reply by Patrick-Bayer** [reply]
Hi @reuvenharrison,

thanks for your response! The two specs are the following

```
components:
    schemas:
        Unternehmen:
            type: object
            properties:
                id:
                    type: number
                    format: float
```

```
components:
    schemas:
        Unternehmen:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
```

The diff would then be

```
GET /unternehmen
- Responses changed
  - Modified response: 200
    - Content changed
      - Modified media type: application/json
        - Schema changed
          - Items changed
            - Properties changed
              - Modified property: id
                - Type changed from 'number' to 'integer'
                - Format changed from 'float' to 'int64'
```
